FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3 python3-pip python3-dev tini

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

RUN pip3 install odoopbx
RUN odoopbx install agent
RUN apt-get clean
CMD ["odoopbx", "run", "agent"]